.\"	$Id$
.Dd January 25, 2002
.Dt PKTSTAT 1
.Os
.Sh NAME
.Nm pktstat
.Nd display packet activity on a crt
.Sh SYNOPSIS
.\" For a program:  program [-abc] file ...
.Nm pktstat
.Op Fl BcFnt
.Op Fl i Ar interface
.Op Fl k Ar keepcount
.Op Fl w Ar waittime
.Op Ar filter-expr
.Sh DESCRIPTION
The
.Nm
program displays a real-time summary of packet activity on an interface.
Each line displays the data associated with a particular class of packets.
Normally, the class is determined by the packet header.
.Pp
.Bl -tag -width 12ex -offset indent
.It Fl B
Dispay data rates in bytes per second (Bps) instead of
in bits per second (bps).
.It Fl c
Do not combine packet classes into one class. For example, TCP flows
are shown as separate streams.
.It Fl F
Show full hostnames.
Normally, hostnames are truncated to the first component of their domain name
before display.
.It Fl i Ar interface
Listen on the given interface instead of using a default one.
.It Fl k Ar keepcount
When no data has been seen for a particular class, retain an entry
on the display for this many screen refreshes.
Default 10.
.It Fl n
Do not try and resolve hostnames or service port numbers.
(DNS lookups can stall display updates.)
.It Fl t
"Top" mode.
Sorts the display by octet count, rather than by
the packet class.
.It Fl w Ar waittime
Refresh the display every
.Ar waittime
seconds.
The default is 5 seconds.
.It Ar filter-expr
Ignore all data not matching the given filter-expression.
If no filter is provided, every packet is considered.
.El
.Pp
If the terminal supports it, the display briefly highlights in bold
new connections or old connections carrying data after a period
of inactivity.
.Pp
During display, the following keystrokes are recognised:
.Bl -tag -width Ic -offset indent
.It Ic q
quit
.It Ic Ctrl-L
redraw screen
.It Ic t
toggle the
.Fl t
flag (top mode)
.It Ic n
toggle the
.Fl n
flag (numeric display)
.It Ic b | B
toggle the
.Fl B
flag (bps or Bps)
.It Ic f | F
toggle the
.Fl F
flag (full hostnames)
.El
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh EXAMPLES
.\" This next request is for sections 2 and 3 function return values only.
.\" .Sh RETURN VALUES
.\" The next request is for sections 2 and 3 error and signal handling only.
.\" .Sh ERRORS
.\" This next request is for section 4 only.
.\" .Sh DIAGNOSTICS
.\" This next request is for sections 1, 6, 7 & 8 only.
.\" .Sh ENVIRONMENT
.\" .Sh FILES
.Sh SEE ALSO
.Xr bpf 4 ,
.Xr tcpdump 8
.\" .Sh COMPATIBILITY
.\" .Sh STANDARDS
.Sh AUTHORS
David Leonard,
.Pa d+pktstat@itee.uq.edu.au
.\" .Sh HISTORY
.Sh BUGS
DNS lookups can take too much time, leading to missed packets.
The data rates do not take into account datalink framing or compression.
Keystrokes are only recognised at the time the screen is refreshed.
.\" .Sh CAVEATS
