.\"	$Id$
.Dd January 25, 2002
.Dt PKTSTAT 1
.Os
.Sh NAME
.Nm pktstat
.Nd display packet activity on a crt
.Sh SYNOPSIS
.Nm pktstat
.Op Fl BcFlntT
.Op Fl a Ar abbrev
.Op Fl A Ar file
.Op Fl i Ar interface
.Op Fl k Ar keeptime
.Op Fl w Ar waittime
.Op Ar filter-expr
.Sh DESCRIPTION
The
.Nm
program displays a real-time summary of packet activity on an interface.
Each line displays the data associated with a particular class of packets.
Normally, the class is determined by the packet header.
.Pp
.Nm
understands the following command line options:
.Bl -tag -width 12ex -offset indent
.It Fl a Ar abbrev
Add
.Ar abbrev
to the list of abbreviation patterns.

.It Fl A Ar file
Read abbreviation patterns from the given file.
Abbreviation patterns must be on separate lines.
Leading and trailing whitespace is ignored;
blank lines and lines starting with
.Ql #
are ignored.
.It Fl B
Display data rates in bytes per second (Bps) instead of
in bits per second (bps).
.It Fl c
Do not combine some packet classes into one class.
For example, TCP connections are kept as two separate flows.
.\" .It Fl E
.\" Don't exit on errors from the
.\" .Xr pcap 3
.\" library.
.It Fl F
Show full hostnames.
Normally, hostnames are truncated to the first component of their domain name
before display.
.It Fl i Ar interface
Listen on the given interface.
If not specified, a suitable interface is chosen.
.It Fl k Ar keeptime
When no packets have been seen for a particular class,
retain an entry on the display for this many screen seconds.
Defaults to 10.
.It Fl l
Display and sort flows by when they were last seen.
(Incompatible with
.Fl t )
.It Fl n
Do not try and resolve hostnames or service port numbers.
.It Fl t
"Top" mode.
Sorts the display by octet count, rather than by
the packet class.
.It Fl T
Show bit (byte) totals for flows.
.It Fl w Ar waittime
Refresh the display every
.Ar waittime
seconds.
The default is 5 seconds.
.It Ar filter-expr
Ignore all data not matching the given filter-expression.
If no filter is provided, all packets are considered.
.El
.Pp
If the terminal supports it, the display briefly highlights in bold
new connections or old connections carrying data after a period
of inactivity.
.Pp
Simple statistics about the interface are also displayed such as 
the current and average bit rates (measured just above the data link layer).
Load averages refer to bit rate decayed averages for the last 1, 5 and 15
minutes.
.Pp
During display, the following keystrokes are recognised:
.Bl -tag -width Ic -offset indent
.It Ic q
quit
.It Ic Ctrl-L
redraw screen
.It Ic t
toggle the
.Fl t
flag (top mode)
.It Ic T
toggle the
.Fl T
flag (totals mode)
.It Ic n
toggle the
.Fl n
flag (numeric display)
.It Ic b | B
toggle the
.Fl B
flag (bps or Bps)
.It Ic f | F
toggle the
.Fl F
flag (full hostnames)
.It Ic r
reset collected statistics (min, max, etc.),
flush flow history and reset DNS/service caches
.It Ic l
show and sort flows by when they were last active
.It Ic ?
display a short help message at the bottom of the display
.El
.Ss Packet classes
.Pp
All packet classes, or flows, are
.Qq tagged
with a descriptive string, such as
.Ql "tcp ftpserver:20524 <-> cathexis:17771" .
.Pp
In addition to being tagged, some protocol-state information can
be associated with a flow. This is displayed immediately below a flow line.
Descriptive information for FTP, HTTP, and X11 connections is determined
from simple decoding of some packets.
.\"
.Ss Abbreviations
.Pp
Abbreviation patterns are a way of further combining flows.
As packets are decoded, their flow name is constructed at the various
protocol layers. At address combining stage (where arrows such as
.Ql "->"
are inserted)
and at the final display stage, names are checked against
a list of abbreviation patterns, and
and the abbreviation's name substituted if a match is found.
For example, the pattern
.Ql "* <-> *:domain"
will match DNS packets in both the UDP and TCP layers.
.Pp
Abbreviations Take the form
.Op Ar name Ns Li @ Ns
.Ar pattern .
The
.Ar pattern
part can contain the wildcard character, asterisk
.Ql *
which matches zero or more non-space characters.
The space character
matches one or more whitespace characters.
.Pp
If the optional
.Ar name
is not specified, the the pattern text itself is used as the name.
.Pp
Patterns are checked in the order given on the command line or in the file.
So, as soon as one of the patterns matches, the rest are ignored at that
stage.
Recall that patterns can be applied multiple times on a tag.
.Pp
A file of patterns can contain blank lines. Comment lines that
commence with a
.Ql #
character are also ignored.
.Pp
After processing command line arguments,
.Nm pktstat
then looks for and loads
.Pa ".pktstatrc" ,
.Pa $HOME/.pktstatrc
and
.Pa /etc/pktstatrc .
(This behaviour is suppressed if an empty argument is given to the
.Fl A
option.)
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh EXAMPLES
.\" This next request is for sections 2 and 3 function return values only.
.\" .Sh RETURN VALUES
.\" The next request is for sections 2 and 3 error and signal handling only.
.\" .Sh ERRORS
.\" This next request is for section 4 only.
.\" .Sh DIAGNOSTICS
.\" This next request is for sections 1, 6, 7 & 8 only.
.\" .Sh ENVIRONMENT
.\" .Sh FILES
.Sh SEE ALSO
.Xr bpf 4 ,
.Xr tcpdump 8
.\" .Sh COMPATIBILITY
.\" .Sh STANDARDS
.Sh AUTHORS
David Leonard,
.Pa d+pktstat@itee.uq.edu.au
.\" .Sh HISTORY
.Sh BUGS
.Pp
DNS lookups can take too much time, possibly leading to missed packets.
.Pp
The data rates do not take into account data link framing overhead or
compression savings at the data link layer.
.Pp
The direction of traffic is not taken into account: both ingress and
egress data rates are combined. If you want to separate them, you will need
to use a filter expression.
.Pp
Descriptive information for X11, FTP and HTTP flows is derived from the
very first packets sent on those protocols.
If you start
.Nm
after any of these flows have commenced, there will be no description
available for them.
.\" .Sh CAVEATS
